name: Release Proto

on:
  push:
    branches:
      - main

permissions:
  contents: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24

      - name: Get latest tag
        id: get_tag
        run: |
          TAG=$(git describe --tags --abbrev=0 || echo "v0.0.0")
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Bump version
        id: bump
        run: |
          OLD_TAG=${{ steps.get_tag.outputs.tag }}
          OLD_VER=${OLD_TAG#v}
          IFS='.' read -r MAJOR MINOR PATCH <<< "$OLD_VER"
          NEW_TAG="v0.$((MINOR+1)).0"
          echo "new_tag=$NEW_TAG" >> $GITHUB_OUTPUT

      - name: Create and push new tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          NEW_TAG=${{ steps.bump.outputs.new_tag }}

          # Проверяем, существует ли такой тег на удалённом репозитории
          if git ls-remote --tags origin | grep -q "refs/tags/$NEW_TAG"; then
            COMMIT_SHA=$(git rev-parse --short HEAD)
            NEW_TAG="${NEW_TAG}-${COMMIT_SHA}"
            echo "Tag already exists, using unique tag: $NEW_TAG"
          fi

          # Создаём и пушим тег
          git tag $NEW_TAG
          git push origin $NEW_TAG
